version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:latest
    command: minio server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio:
